### ISSUE TITLE
Loading Project

### ISSUE THREAD

**Issue by neoof86** [tomhollander/PowerwallCompanion#1]
Hi Tom,

Just wanted to say amazing work! I was trying to look at the source as I was wondering if I could add some further time ranges seeing as the main iOS and Andriod app support this but I was trying to see how you were querying the today and yesterday from the Tesla motors API

I got the below and I have I just loaded in a module wrong or is there a specific path all these files want to be in?

![LoadErrors](https://user-images.githubusercontent.com/19991728/76700078-93015400-66ab-11ea-82b3-b1a51363f012.PNG)

**Comment by tomhollander** [comment]
Closing since so much time has past. FWIW the app now supports historical data with different time periods.
