### ISSUE TITLE
Export appends to target file instead of overwriting

### ISSUE THREAD

**Issue by peppersass** [tomhollander/PowerwallCompanion#14]
Title says it all.

Previous versions overwrote the target file.  It's debatable whether the app should append or overwrite, but in my workflow overwrite is best. For example, sometimes I need to replace faulty Day files created by the Tesla app and would rather not have to delete the file before the export or remove the old data after the export. In another case, I've added a feature to my data analysis app that relies on the day-by-day information in the Month export file. Each day, I download both the Day file from the previous day and the updated Month file. I have to delete the old Month file to avoid the append.

If append is a feature, not a bug, I'd rather not see a prompt asking whether I want to append or overwrite. Perhaps a Setting for append or overwrite is the way to go.

**Comment by tomhollander** [comment]
Thanks, this wasn't deliberate. I'll look into this when I get some time.

**Comment by tomhollander** [comment]
Fixed in 5.3.2.
