### ISSUE TITLE
Yesterdays "Used by Home" mouse over incorrect

### ISSUE THREAD

**Issue by tmcgough** [tomhollander/PowerwallCompanion#19]
On Windows App version  9.0.0.0, wen you mouse over the Yesterdeay column for the house consumption, the mouse over popup is showing the Today value instead of the Yesterday value.   The actual screen shows correctly, just the mouse over has the wrong value.

"XXX used by home yesterday"    shows the same value as the "XXX used by home today".

This is just in the mouse over notice and not the displayed values in the columns.

This is an awesome App. Love it greatly.

**Comment by tmcgough** [comment]
This is also true in the 9.1.0.0 I just updated to today.

**Comment by tomhollander** [comment]
Thanks, will fix.

**Comment by tomhollander** [comment]
Fixed in 9.1.1
