### ISSUE TITLE
plotting option suggestion

### ISSUE THREAD

**Issue by David-Devon** [tomhollander/PowerwallCompanion#2]
I would like to be able to read the y-axis as kWh instead of persentage. 

The correlation between % and kWh will depend upon the size of the battery (at present 13.5kWh, but maybe different for future batteries) and the age of the battery (and maybe different summer to winter?).
Have an tick-box option to display in kWh, with a multiplier to perform the transformation that can be set by the user.
And also have an option to show the 0.5 kWh reserve that keeps the battery sane.

I don't know what information is available from the gateway but I suspect that the percentage is a derived parameter, so the kWh parameter would be more accurate and save me having find bits of information from other places and doing the calculation with imprecise data.

Thanks for the nice app,
regards,
David.

**Comment by tomhollander** [comment]
Closing since so much time has passed. The app now has much improved charting. The battery SoC still shows as a % since that's what's available in the API, although you can see your current storage capacity in the new Battery Status page.
