### ISSUE TITLE
Tesla changed their authenticaion schema

### ISSUE THREAD

**Issue by michaelvorst** [tomhollander/PowerwallCompanion#3]
Looks like the app can not log in any more now that my token has expired, I'm seeing other apps with the same issue and devs commenting that Tesla changed something.

**Comment by tomhollander** [comment]
Yep, I'm on it. I'll try to get an update out over the next couple of days. In the meantime the app should still work if you connect directly to the gateway.

**Comment by tomhollander** [comment]
Try again now. Code is in this repo, or use the new version 2.6.0 from the Windows Store.
I expect some teething issues so let me know how it goes.
