### ISSUE TITLE
MFA code

### ISSUE THREAD

**Issue by craigf48** [tomhollander/PowerwallCompanion#5]
Hi Tom,
The Powerwall Companion has a new "MFA Code" field which I don't want to use.  However if I leave it blank it errors.  Is it possible to have a switch that can make this field optional?  I don't use MFA on my Tesla account and I don't want to.
Thanks
Craig

**Comment by tomhollander** [comment]
Hi @craigf48 - the MFA code is optional, but over the last week the app hasn't worked well due to some changes on Tesla's side. I just pushed an update to the store (and this repo) which should fix the issues, plus it makes it clear that MFA is optional.
